--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/KumaaDeveloper/ServerCensored
build-by-default: true
branches:
- main
projects:
  ServerCensored:
    path: ""
    icon: icon.png
...
